version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meta_store
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # will run on DB start
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    env_file: ./api-server/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - shared-volume:/data
    ports:
      - "3000:3000"

  file-processor:
    build:
      context: ./file-processor
      dockerfile: Dockerfile
    env_file: ./file-processor/.env
    volumes:
      - shared-volume:/data
    depends_on:
      - postgres
      - redis
      - api-server
volumes:
  pgdata:
  shared-volume:
