version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meta_store
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # will run on DB start
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # api-server:
  #   build:
  #     context: ./api-server
  #     dockerfile: Dockerfile
  #   env_file: ./api-server/.env
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: appdb
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   ports:
  #     - "3000:3000"
  #   command: >
  #     sh -c "
  #     ./wait-for-postgres.sh &&
  #     npm start
  #     "

  file-processor:
    build:
      context: ./file-processor
      dockerfile: Dockerfile
    env_file: ./file-processor/.env
    depends_on:
      - postgres
      - redis
      # - api-server
volumes:
  pgdata:
